import { Agent, AgentEvent } from '@/types/agent';
import { ApprovalRequest } from '@/types/approval';
import { ContextPacket } from '@/types/context';
import { MemoryRecord, SessionCheckpoint, DecisionRecord } from '@/types/memory';
import { MCPTool, MCPResource, MCPConnection } from '@/types/mcp';

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'ag-coder-01',
    name: 'ContextOS Core Coder',
    type: 'CODER',
    provider: 'OpenAI / Codex',
    model: 'gpt-4o',
    status: 'RUNNING',
    current_task: 'Implementing ApprovalCard component with shadcn/ui and assistant-ui patterns',
    tokens: {
      candidate_tokens: 34200,
      selected_tokens: 4150,
      excluded_tokens: 30050,
      estimated_tokens_avoided: 30050,
      cache_hits: 12,
      total_input_tokens: 4150,
      total_output_tokens: 1280,
      reused_cached_tokens: 1840,
    },
    context_size: 4150,
    runtime_seconds: 412,
    project_id: 'contextos',
    session_id: 'sess-active-01',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    started_at: new Date(Date.now() - 412000).toISOString(),
    last_activity_at: new Date(Date.now() - 4000).toISOString(),
    permissions: {
      can_execute_shell: true,
      can_edit_files: true,
      can_git_commit: true,
      can_network: false,
    },
  },
  {
    id: 'ag-planner-01',
    name: 'Architecture Planner',
    type: 'PLANNER',
    provider: 'Antigravity (AGY)',
    model: 'gemini-2.5-pro',
    status: 'COMPLETED',
    current_task: 'Compiled Target Architecture blueprint & Open Source Software reuse plan',
    tokens: {
      candidate_tokens: 48000,
      selected_tokens: 6200,
      excluded_tokens: 41800,
      estimated_tokens_avoided: 41800,
      cache_hits: 8,
      total_input_tokens: 6200,
      total_output_tokens: 2400,
      reused_cached_tokens: 3100,
    },
    context_size: 6200,
    runtime_seconds: 780,
    project_id: 'contextos',
    session_id: 'sess-arch-01',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    started_at: new Date(Date.now() - 7200000).toISOString(),
    last_activity_at: new Date(Date.now() - 3600000).toISOString(),
    permissions: {
      can_execute_shell: false,
      can_edit_files: true,
      can_git_commit: false,
      can_network: false,
    },
  },
  {
    id: 'ag-reviewer-01',
    name: 'Security & Diff Reviewer',
    type: 'REVIEWER',
    provider: 'OpenAI / Codex',
    model: 'o3-mini',
    status: 'WAITING_APPROVAL',
    current_task: 'Reviewing uncommitted git patch for path jailing and shell timeout policy',
    tokens: {
      candidate_tokens: 18500,
      selected_tokens: 3100,
      excluded_tokens: 15400,
      estimated_tokens_avoided: 15400,
      cache_hits: 4,
      total_input_tokens: 3100,
      total_output_tokens: 850,
      reused_cached_tokens: 950,
    },
    context_size: 3100,
    runtime_seconds: 145,
    project_id: 'contextos',
    session_id: 'sess-rev-01',
    created_at: new Date(Date.now() - 1800000).toISOString(),
    started_at: new Date(Date.now() - 145000).toISOString(),
    last_activity_at: new Date(Date.now() - 12000).toISOString(),
    permissions: {
      can_execute_shell: false,
      can_edit_files: false,
      can_git_commit: false,
      can_network: false,
    },
  },
  {
    id: 'ag-tester-01',
    name: 'Playwright & Unit Tester',
    type: 'TESTER',
    provider: 'Antigravity (AGY)',
    model: 'gemini-2.5-flash',
    status: 'IDLE',
    current_task: 'Awaiting completion of Control Center UI build before launching Playwright harness',
    tokens: {
      candidate_tokens: 0,
      selected_tokens: 0,
      excluded_tokens: 0,
      estimated_tokens_avoided: 0,
      cache_hits: 0,
      total_input_tokens: 0,
      total_output_tokens: 0,
    },
    context_size: 0,
    runtime_seconds: 0,
    project_id: 'contextos',
    session_id: 'sess-test-01',
    created_at: new Date(Date.now() - 900000).toISOString(),
    last_activity_at: new Date(Date.now() - 900000).toISOString(),
    permissions: {
      can_execute_shell: true,
      can_edit_files: true,
      can_git_commit: false,
      can_network: true,
    },
  },
  {
    id: 'ag-researcher-01',
    name: 'OSS Dependency Investigator',
    type: 'RESEARCHER',
    provider: 'Antigravity (AGY)',
    model: 'gemini-2.5-flash',
    status: 'COMPLETED',
    current_task: 'Audited openmemory, mem0, assistant-ui, and OpenHands licenses and commit SHAs',
    tokens: {
      candidate_tokens: 52000,
      selected_tokens: 5400,
      excluded_tokens: 46600,
      estimated_tokens_avoided: 46600,
      cache_hits: 15,
      total_input_tokens: 5400,
      total_output_tokens: 1900,
      reused_cached_tokens: 2800,
    },
    context_size: 5400,
    runtime_seconds: 520,
    project_id: 'contextos',
    session_id: 'sess-res-01',
    created_at: new Date(Date.now() - 10800000).toISOString(),
    started_at: new Date(Date.now() - 10800000).toISOString(),
    last_activity_at: new Date(Date.now() - 5400000).toISOString(),
    permissions: {
      can_execute_shell: false,
      can_edit_files: false,
      can_git_commit: false,
      can_network: true,
    },
  },
];

export const INITIAL_EVENTS: AgentEvent[] = [
  {
    id: 'evt-001',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'agent.started',
    timestamp: new Date(Date.now() - 410000).toISOString(),
    payload: { role: 'CODER', task: 'Implement approval card and layout' },
  },
  {
    id: 'evt-002',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'context.generated',
    timestamp: new Date(Date.now() - 395000).toISOString(),
    payload: { tier0_tokens: 850, tier1_tokens: 1200, tier2_tokens: 1400, tier3_tokens: 700, avoided_tokens: 30050 },
  },
  {
    id: 'evt-003',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'file.read',
    timestamp: new Date(Date.now() - 320000).toISOString(),
    payload: { path: 'web/src/types/approval.ts', lines: 35 },
  },
  {
    id: 'evt-004',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'agent.thinking',
    timestamp: new Date(Date.now() - 250000).toISOString(),
    payload: { thought: 'ApprovalCard must support Approve once, Approve for session, and Reject with risk severity colors' },
  },
  {
    id: 'evt-005',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'tool.requested',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    payload: { tool: 'file_editor.write', target: 'web/src/components/approval/ApprovalCard.tsx' },
  },
  {
    id: 'evt-006',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'file.changed',
    timestamp: new Date(Date.now() - 170000).toISOString(),
    payload: { file: 'web/src/components/approval/ApprovalCard.tsx', insertions: 84, deletions: 0 },
  },
  {
    id: 'evt-007',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    type: 'tool.approval_required',
    timestamp: new Date(Date.now() - 15000).toISOString(),
    payload: {
      action: 'shell_command',
      command: 'git push origin main',
      risk: 'HIGH',
      affected_resource: 'git:remote',
    },
  },
];

export const INITIAL_APPROVALS: ApprovalRequest[] = [
  {
    id: 'appr-001',
    agent_id: 'ag-coder-01',
    session_id: 'sess-active-01',
    action_type: 'shell_command',
    action_name: 'terminal.execute',
    command: 'git push origin main',
    arguments: { command: 'git push origin main', working_directory: 'c:/Users/rc821/OneDrive/Desktop/ContextOS' },
    risk_level: 'HIGH',
    affected_resource: 'git:remote/origin/main',
    reason: 'Agent is attempting to push newly committed changes to remote repository branch main.',
    timestamp: new Date(Date.now() - 15000).toISOString(),
    status: 'PENDING',
  },
  {
    id: 'appr-002',
    agent_id: 'ag-reviewer-01',
    session_id: 'sess-rev-01',
    action_type: 'delete_file',
    action_name: 'file_editor.delete',
    arguments: { path: 'c:/Users/rc821/OneDrive/Desktop/ContextOS/scratch/temp_token_dump.json' },
    risk_level: 'MEDIUM',
    affected_resource: 'scratch/temp_token_dump.json',
    reason: 'Agent cleanup of scratch diagnostic file generated during prompt token analysis.',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    status: 'PENDING',
  },
];

export const INITIAL_CONTEXT_PACKET: ContextPacket = {
  id: 'ctx-001',
  task_id: 'task-web-ui',
  project_id: 'contextos',
  created_at: new Date().toISOString(),
  budget: {
    total_budget_tokens: 8000,
    system_reserved_percent: 15,
    task_percent: 10,
    decisions_memory_percent: 15,
    source_tests_percent: 50,
    buffer_percent: 10,
  },
  metrics: {
    raw_candidate_tokens: 34200,
    selected_tokens: 4150,
    excluded_tokens: 30050,
    estimated_tokens_avoided: 30050,
    reduction_percentage: 87.8,
    cache_hits: 12,
  },
  candidates: [
    {
      id: 'c-1',
      source: 'task',
      title: 'Prompt 2 UI Task Specification',
      raw_tokens: 480,
      relevance_score: 1.0,
      tier: 0,
      included: true,
      inclusion_reason: 'Active task definition (Tier 0 required)',
      preview: 'Build AIOS Web Control Center with 10 sidebar links, live activity stream, and approval card.',
    },
    {
      id: 'c-2',
      source: 'git_diff',
      title: 'Uncommitted Git Diff (README & docs)',
      raw_tokens: 370,
      relevance_score: 0.98,
      tier: 0,
      included: true,
      inclusion_reason: 'Current uncommitted workspace modifications',
      preview: '+ [Target Architecture](docs/TARGET_ARCHITECTURE.md)\n+ [Open-Source Reuse Plan](docs/OSS_REUSE_PLAN.md)',
    },
    {
      id: 'c-3',
      source: 'symbol',
      title: 'Agent, AgentRole, AgentStatus interfaces',
      path: 'web/src/types/agent.ts',
      range: 'L1-L55',
      raw_tokens: 420,
      relevance_score: 0.95,
      tier: 1,
      included: true,
      inclusion_reason: 'Public exported symbol interfaces (Tier 1)',
      preview: 'export type AgentRole = "PLANNER" | "CODER" | ...',
    },
    {
      id: 'c-4',
      source: 'source_file',
      title: 'ApprovalCard Component Implementation',
      path: 'web/src/components/approval/ApprovalCard.tsx',
      range: 'L1-L120',
      raw_tokens: 1400,
      relevance_score: 0.92,
      tier: 2,
      included: true,
      inclusion_reason: 'Target file actively being edited',
      preview: 'export function ApprovalCard({ request, onApprove, onReject }) { ... }',
    },
    {
      id: 'c-5',
      source: 'decision',
      title: 'ADR-004: Strict 4-Tier Context Hierarchy',
      path: 'docs/TARGET_ARCHITECTURE.md#tier-4',
      raw_tokens: 650,
      relevance_score: 0.85,
      tier: 3,
      included: true,
      inclusion_reason: 'Architectural constraint relevant to token budgeting',
      preview: 'Tier 0 task, Tier 1 signatures, Tier 2 target bodies, Tier 3 semantic history.',
    },
    {
      id: 'c-6',
      source: 'source_file',
      title: 'LICENSE Full Text (202 lines)',
      path: 'LICENSE',
      raw_tokens: 2800,
      relevance_score: 0.12,
      tier: 2,
      included: false,
      exclusion_reason: 'Excluded by budget: Static legal text has no functional impact on UI build.',
    },
    {
      id: 'c-7',
      source: 'source_file',
      title: 'node_modules directory & lockfiles',
      raw_tokens: 27250,
      relevance_score: 0.0,
      tier: 2,
      included: false,
      exclusion_reason: 'Strict rule: Excluded by directory boundary filter (node_modules).',
    },
  ],
  tier0_task_and_diff: {
    task_spec: 'Build desktop-first AIOS Control Center with 10 sidebar items, topbar stats, split workspace, approval UI.',
    git_diff_summary: '3 files changed: .gitignore, README.md, docs/TARGET_ARCHITECTURE.md',
  },
  tier1_signatures: [
    { symbol: 'Agent', file: 'web/src/types/agent.ts', signature: 'interface Agent { id: string; name: string; type: AgentRole; status: AgentStatus; ... }' },
    { symbol: 'ApprovalRequest', file: 'web/src/types/approval.ts', signature: 'interface ApprovalRequest { id: string; risk_level: RiskLevel; status: string; ... }' },
  ],
  tier2_target_bodies: [
    { file: 'web/src/components/approval/ApprovalCard.tsx', lines: '1-120', content: '// Source body of human approval component' },
  ],
  tier3_semantic_history: {
    decisions: [
      'ADR-001: Modular Monolith architecture chosen to eliminate local networking latency.',
      'ADR-003: Sandboxed Process Group Supervision & Path Jailing enforced.',
    ],
    failures: [
      'Identified sandboxed Windows AppContainer network blockage during runtimes check; bypassed appropriately for external tooling.',
    ],
    guidelines: [
      'Never fake backend execution. Explicitly mark pending endpoints.',
      'Auditable token math: Tokens Avoided = Candidate Tokens - Dispatched Tokens.',
    ],
  },
};

export const INITIAL_MEMORIES: MemoryRecord[] = [
  {
    id: 'mem-001',
    project_id: 'contextos',
    type: 'decision',
    title: 'ADR-001: Modular Monolith Pattern',
    content: 'ContextOS is structured as a Modular Monolith with web/ frontend and server/ daemon to eliminate distributed container complexity locally.',
    summary: 'Single-repository modular architecture with unified typing.',
    source: 'docs/TARGET_ARCHITECTURE.md',
    importance: 9,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
    last_accessed_at: new Date(Date.now() - 60000).toISOString(),
    access_count: 14,
  },
  {
    id: 'mem-002',
    project_id: 'contextos',
    type: 'failure',
    title: 'Terminal Sandbox Isolation on Windows',
    content: 'Windows AppContainer sandbox blocks out-of-boundary access without BypassSandbox flag. Development builds need explicit bypass permission.',
    summary: 'Sandbox policy and bypass guidelines for host compilers and runtimes.',
    source: 'runtime_telemetry',
    importance: 8,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    last_accessed_at: new Date(Date.now() - 120000).toISOString(),
    access_count: 6,
  },
  {
    id: 'mem-003',
    project_id: 'contextos',
    type: 'semantic',
    title: 'Strict 4-Tier Context Selection Hierarchy',
    content: 'Context packets must compile across 4 tiers: Tier 0 Task/Diff, Tier 1 Signatures/Stubs, Tier 2 Target Code, Tier 3 Semantic/Decisions.',
    summary: 'Rules for compiling context packets without repository dumping.',
    source: 'docs/TARGET_ARCHITECTURE.md',
    importance: 10,
    created_at: new Date(Date.now() - 5400000).toISOString(),
    updated_at: new Date(Date.now() - 5400000).toISOString(),
    last_accessed_at: new Date(Date.now() - 30000).toISOString(),
    access_count: 22,
  },
  {
    id: 'mem-004',
    project_id: 'contextos',
    type: 'code_reference',
    title: 'Normalized Event Envelope Specification',
    content: 'All agent and system events follow { id, agent_id, session_id, type, timestamp, payload } envelope format.',
    summary: 'Universal WebSocket event payload structure.',
    source: 'server/contextos/api/events.py',
    importance: 8,
    created_at: new Date(Date.now() - 4000000).toISOString(),
    updated_at: new Date(Date.now() - 4000000).toISOString(),
    last_accessed_at: new Date(Date.now() - 200000).toISOString(),
    access_count: 9,
  },
];

export const INITIAL_CHECKPOINTS: SessionCheckpoint[] = [
  {
    id: 'chk-01',
    project_id: 'contextos',
    session_id: 'sess-active-01',
    goal: 'Build Phase 2 AIOS Web Control Center and Approval UI',
    completed_items: [
      'Initialize Vite + React 19 + TypeScript + Tailwind CSS in web/',
      'Create types for agents, approvals, context packets, and memory',
      'Establish left sidebar navigation with 10 core views',
    ],
    current_task: 'Wire live activity stream and human approval card',
    remaining_items: [
      'Implement Agent detail view with 9 inspection tabs',
      'Connect WebSocket event bus',
      'Verify build and lint clean',
    ],
    decisions: [
      'Use shadcn/ui and Tailwind CSS for rapid accessible dashboard styling',
      'Render ApprovalCard for shell commands, deletions, and git pushes',
    ],
    failures: [],
    important_files: [
      'web/src/components/approval/ApprovalCard.tsx',
      'web/src/pages/DashboardPage.tsx',
      'web/src/pages/AgentsPage.tsx',
    ],
    modified_files: [
      'web/src/types/agent.ts',
      'web/src/types/approval.ts',
      'web/src/types/context.ts',
    ],
    git_branch: 'main',
    git_commit: 'd0cd81a',
    tests_status: 'PASSING',
    next_action: 'Test frontend production build',
    created_at: new Date(Date.now() - 300000).toISOString(),
  },
];

export const INITIAL_MCP_TOOLS: MCPTool[] = [
  { name: 'project_get', description: 'Retrieve root workspace metadata, configuration, and security boundary', parameters: { project_id: 'string' }, category: 'agent' },
  { name: 'project_status', description: 'Query active branch, git diff summary, running agent count, and memory size', parameters: {}, category: 'git' },
  { name: 'context_build', description: 'Assemble a 4-tier minimal context packet under strict token budgeting', parameters: { task: 'string', budget_tokens: 'number' }, category: 'context' },
  { name: 'context_search', description: 'Semantic search over symbols, ast signatures, and code ranges', parameters: { query: 'string' }, category: 'context' },
  { name: 'memory_search', description: 'Vector similarity search over persistent decisions, constraints, and failures', parameters: { query: 'string', limit: 'number' }, category: 'memory' },
  { name: 'memory_remember', description: 'Store a durable architectural decision or resolved gotcha', parameters: { type: 'string', title: 'string', content: 'string' }, category: 'memory' },
  { name: 'memory_decision_add', description: 'Record an Architectural Decision Record (ADR) during agent execution', parameters: { title: 'string', decision: 'string', context: 'string' }, category: 'memory' },
  { name: 'session_checkpoint', description: 'Serialize current uncommitted git diff and progress into Universal Handoff Envelope', parameters: { session_id: 'string' }, category: 'session' },
  { name: 'session_resume', description: 'Resume a session without replaying past conversation tokens', parameters: { checkpoint_id: 'string' }, category: 'session' },
  { name: 'session_import', description: 'Import and normalize external agent session from AGY or Codex format', parameters: { source_format: 'string', data: 'object' }, category: 'session' },
  { name: 'agent_list', description: 'List all running, paused, and completed agents with their token telemetry', parameters: {}, category: 'agent' },
  { name: 'agent_status', description: 'Get live status and last activity of a specific agent run', parameters: { agent_id: 'string' }, category: 'agent' },
  { name: 'agent_delegate', description: 'Dispatch a subtask from a PLANNER agent to a CODER or TESTER agent', parameters: { target_role: 'string', task: 'string' }, category: 'agent' },
  { name: 'task_get', description: 'Get details and acceptance criteria of the active task', parameters: { task_id: 'string' }, category: 'task' },
  { name: 'task_update', description: 'Update task progress checklist item or status', parameters: { task_id: 'string', checklist_item: 'string', status: 'string' }, category: 'task' },
  { name: 'git_diff_summary', description: 'Get uncommitted working tree diff stats and touched files', parameters: {}, category: 'git' },
  { name: 'token_metrics', description: 'Get auditable candidate tokens, dispatched tokens, and tokens avoided', parameters: {}, category: 'telemetry' },
];

export const INITIAL_MCP_CONNECTIONS: MCPConnection[] = [
  {
    id: 'mcp-conn-01',
    client_name: 'Antigravity (AGY)',
    transport: 'streamable_http',
    endpoint: 'http://localhost:8000/mcp/v2',
    status: 'CONNECTED',
    last_ping: new Date(Date.now() - 5000).toISOString(),
    calls_count: 48,
  },
  {
    id: 'mcp-conn-02',
    client_name: 'Codex CLI / Client',
    transport: 'stdio',
    endpoint: 'contextos mcp-stdio',
    status: 'CONNECTED',
    last_ping: new Date(Date.now() - 14000).toISOString(),
    calls_count: 31,
  },
];
